import "./globals.css";
import type { Metadata } from "next";
import localFont from 'next/font/local'
import { Inter, Roboto, Aclonica } from "next/font/google";
import NavBar from "./NavBar";
import AuthProvider from "./auth/Provider";
import GoogleAnalyticsScript from "./GoogleAnalyticsScript";


const inter = Inter({ subsets: ["latin"] });

// const roboto = Roboto({subsets: ["latin"], weight: ["400", "500"] });

// const aclonica = Aclonica({subsets: ["latin"], weight: ["400"]});

const poppins = localFont({
  src: '../public/fonts/poppins-regular-webfont.woff2',
  variable: '--font-poppins'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  openGraph: {
    title: '...',
    description: '...'
  }
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const combinedClassNames = `${inter.className} ${poppins.variable}`;
  return (
    <html lang="en" data-theme="winter">
      <GoogleAnalyticsScript/>
      <body className={combinedClassNames}>
        <AuthProvider>
          <NavBar />
          <main className="p-5">{children}</main>
        </AuthProvider>
      </body>
    </html>
  );
}
